services:
  - type: web
    name: my-laravel-app
    env: php
    plan: free # o el plan que prefieras
    buildCommand: "composer install --optimize-autoloader --no-dev && php artisan key:generate"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tu-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: tu-db-name
      - key: DB_USERNAME
        value: tu-db-user
      - key: DB_PASSWORD
        value: tu-db-password